(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const ids=['pinkie','twilight','applejack','rainbow','rarity','fluttershy','xinglan'];
  const portraits=Object.fromEntries(ids.map(id=>[id,'/member-'+id+'-clean.png']));
  const stageNames={opening:'收到任务',ideas:'出主意',challenge:'挑问题',consensus:'说人话',execute:'真执行'};
  const state={token:'',members:{},sessions:[],session:null,messages:new Map(),models:[],run:null,events:null,modelSaving:false,follow:true,runMode:'execute',createPath:'',folderRequests:new Map()};
  const node=(tag,cls='',text='')=>{const value=document.createElement(tag);value.className=cls;value.textContent=text;return value;};
  const toast=text=>{$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,3300);};

  async function api(path,data){
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),path.startsWith('/api/models')?25000:15000);
    try{const response=await fetch(path,{method:data?'POST':'GET',cache:'no-store',signal:controller.signal,headers:data?{'Content-Type':'application/json','X-Roundtable-Token':state.token}:{},body:data?JSON.stringify(data):undefined});const value=await response.json();if(!response.ok)throw new Error(value.error||'圆桌连接暂时中断');return value;}
    catch(error){if(error.name==='AbortError')throw new Error('连接超时，输入内容还在。');throw error;}finally{clearTimeout(timer);}
  }
  const projectName=path=>String(path||'').split('/').filter(Boolean).pop()||'未选择项目';
  const shortPath=path=>String(path||'').replace(/^\/Users\/[^/]+/,'~');
  const formatTime=value=>new Date(value*1000).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
  function friendlyError(text,name){const value=String(text||'');if(/no longer available|not available/i.test(value))return name+'选择的模型已不可用，请在右侧换一个。';if(/network|connection|ECONN|timeout|fetch failed|FailoverError|embedded run/i.test(value))return name+'的连接中断了，现有记录和文件都已保留。';return value.length>220?name+'没有完成这一步，技术详情可以展开查看。':value;}

  window.__laolaoProjectFolderResult=payload=>{const request=state.folderRequests.get(payload?.requestId);if(!request)return;state.folderRequests.delete(payload.requestId);clearTimeout(request.timer);request.resolve(payload);};
  function requestFolder(path=''){
    const bridge=window.webkit?.messageHandlers?.laolaoProjectFolder;
    if(!bridge){const value=window.prompt('粘贴项目文件夹的完整路径',path);return Promise.resolve(value?{path:value,name:projectName(value),cancelled:false}:null);}
    const requestId=crypto.randomUUID?.()||Date.now()+'-'+Math.random();
    return new Promise(resolve=>{const timer=setTimeout(()=>{state.folderRequests.delete(requestId);resolve(null);toast('文件夹选择没有响应，请再试一次。');},120000);state.folderRequests.set(requestId,{resolve,timer});bridge.postMessage({action:'choose',context:'roundtable',requestId,path});});
  }
  function revealProject(path){if(!path)return;const bridge=window.webkit?.messageHandlers?.laolaoProjectFolder;if(bridge)bridge.postMessage({action:'reveal',context:'roundtable',path});else toast(path);}
  async function pickCreateProject(){const result=await requestFolder(state.createPath);if(!result||result.cancelled||!result.path)return;state.createPath=result.path;$('create-project-name').textContent=result.name||projectName(result.path);$('create-project-path').textContent=shortPath(result.path);}
  async function makeCreateProject(){const parent=await requestFolder('');if(!parent||parent.cancelled||!parent.path)return;const name=$('create-title').value.trim()||'新项目';try{const result=await api('/api/projects',{parent:parent.path,name});state.createPath=result.path;$('create-project-name').textContent=result.name;$('create-project-path').textContent=shortPath(result.path);toast('空项目已建立');}catch(error){toast(error.message);}}
  async function bindCurrentProject(){if(!state.session)return;const result=await requestFolder(state.session.path||'');if(!result||result.cancelled||!result.path)return;try{const updated=await api('/api/sessions/'+state.session.id+'/update',{path:result.path});Object.assign(state.session,updated);const index=state.sessions.findIndex(item=>item.id===updated.id);if(index>=0)state.sessions[index]=updated;renderProject();renderSessions();modelWarning();toast('项目目录已固定');}catch(error){toast(error.message);}}

  function renderSessions(){
    $('sessions').replaceChildren();const query=$('session-filter').value.trim().toLowerCase();const items=state.sessions.filter(item=>!item.archived&&item.title.toLowerCase().includes(query));$('session-count').textContent=items.length;
    for(const item of items){const button=node('button','session-item'+(item.id===state.session?.id?' active':''));button.type='button';const glyph=node('span','session-glyph');const copy=node('div');copy.append(node('strong','',item.title),node('small','',(item.path?projectName(item.path):'未绑定项目')+' · '+item.members.length+' 席'));button.append(glyph,copy);button.onclick=()=>selectSession(item.id);$('sessions').append(button);}
  }
  function stageState(){const order=['ideas','challenge','consensus','execute'],active=state.run?.stage,current=order.indexOf(active);for(const item of $('stage-track').children){const index=order.indexOf(item.dataset.stage);item.classList.toggle('active',!!state.run&&item.dataset.stage===active);item.classList.toggle('done',!!state.run&&current>index);}}
  function renderProject(){
    const session=state.session,path=session?.path||'';$('project-card').hidden=!session;$('project-name').textContent=path?projectName(path):'尚未绑定';$('project-path').textContent=path?shortPath(path):'旧圆桌需要补选目录';$('project-open').hidden=!path;$('project-bind').hidden=!!path;$('compose-project-name').textContent=path?projectName(path):'未选择项目';$('compose-project').disabled=!path;$('project-guard').hidden=!session||!!path;$('app').dataset.hasProject=String(!!path);
  }
  function toolCard(message){const details=node('details','tool-card');if(message.status==='running')details.open=true;const lines=String(message.body||'').split('\n'),title=lines.shift()||'工具',kind=/write|edit|patch|file|read|文件|读取|写入|修改/i.test(title)?'file':message.status==='done'?'verify':'run',summary=node('summary');summary.append(node('i','tool-icon '+kind),node('b','',title));if(message.status==='running')summary.append(node('span','','正在运行'));else if(message.status==='failed')summary.append(node('span','','未完成'));else summary.append(node('span','','已完成'));const pre=node('pre','',lines.join('\n')||'这一步已经完成');details.append(summary,pre);return details;}
  function renderMessages(scroll=false){
    const container=$('messages'),ordered=[...state.messages.values()].sort((a,b)=>a.id-b.id),present=new Map([...container.children].map(item=>[Number(item.dataset.id),item]));
    for(const message of ordered){let row=present.get(message.id);const expanded=row?.querySelector('.bubble')?.dataset.collapsed==='false';if(!row){row=node('article');row.dataset.id=message.id;container.append(row);}row.className='';row.replaceChildren();
      if(message.kind==='scene'){row.className='scene';row.textContent=message.body;continue;}
      if(message.sender==='user'){row.className='message user';row.append(node('div','bubble',message.body));continue;}
      const info=state.members[message.sender]||{name:message.sender==='workbench'?'执行席':'圆桌记录'},isError=message.kind==='error';
      if(message.kind==='tool'){row.className='message tool '+message.status;row.append(toolCard(message));continue;}
      row.className='message '+message.status+(isError?' error':'')+(message.kind==='progress'?' progress':'')+(message.kind==='summary'?' summary':'');
      if(portraits[message.sender]){const image=node('img','portrait');image.src=portraits[message.sender];image.alt='';image.draggable=false;row.append(image);}else row.append(node('span','system-crystal','◇'));
      const main=node('div','message-main'),meta=node('div','meta');meta.append(node('strong','',info.name||message.sender),node('span','',formatTime(message.created)));if(message.stage&&stageNames[message.stage])meta.append(node('span','stage-label',stageNames[message.stage]));if(message.status==='running')meta.append(node('span','speaking','处理中'));
      const bubble=node('div','bubble'),visible=isError?friendlyError(message.body,info.name||'这一席'):message.body,text=node('div','bubble-text',visible);if(message.kind==='summary')bubble.append(node('i','summary-mark'));bubble.append(text);
      if(isError&&visible!==message.body){const details=node('details','error-details');details.append(node('summary','','技术详情'),node('pre','',message.body));bubble.append(details);}
      if(!isError&&message.kind!=='summary'&&message.body.length>520){bubble.dataset.collapsed=expanded?'false':'true';const more=node('button','message-expand',expanded?'收起':'展开完整内容');more.type='button';more.onclick=()=>{const open=bubble.dataset.collapsed==='true';bubble.dataset.collapsed=String(!open);more.textContent=open?'收起':'展开完整内容';};bubble.append(more);}
      main.append(meta,bubble);row.append(main);
    }
    $('empty').hidden=!!state.session;$('messages').hidden=!state.session;if(scroll&&state.follow)$('timeline').scrollTop=$('timeline').scrollHeight;syncJumpLatest();
  }
  function syncJumpLatest(){const timeline=$('timeline'),near=timeline.scrollHeight-timeline.scrollTop-timeline.clientHeight<120;if(near)state.follow=true;$('jump-latest').hidden=!state.session||near;}
  function selectedModelOptions(value){const select=node('select'),blank=node('option','','选择模型…');blank.value='';select.append(blank);for(const model of state.models){const option=node('option','',model.name);option.value=model.id;option.title=model.id;select.append(option);}if(value&&![...select.options].some(option=>option.value===value)){const missing=node('option','',value+'（不可用）');missing.value=value;select.append(missing);}select.value=value||'';return select;}
  function renderSeats(){
    $('seats').replaceChildren();const selected=new Set(state.session?.members||[]),active=new Set([...state.messages.values()].filter(item=>item.status==='running').map(item=>item.sender));const executor=state.session?.members.includes('xinglan')?'xinglan':state.session?.members.at(-1);
    for(const [id,info] of Object.entries(state.members)){if(state.session&&!selected.has(id))continue;const row=node('div','seat'+(active.has(id)?' active':''));const image=node('img');image.src=portraits[id];image.alt=info.name;const copy=node('div','seat-copy'),title=node('div','seat-name');title.append(node('strong','',info.name),node('i'));copy.append(title,node('small','',info.role+(id===executor?' · 落地执行':'')));const picker=selectedModelOptions(state.session?.models?.[id]||'');picker.disabled=!state.session||!!state.run||state.modelSaving;picker.setAttribute('aria-label','为'+info.name+'选择模型');picker.onchange=()=>saveModel(id,picker.value);copy.append(picker);row.append(image,copy);$('seats').append(row);}
    $('seat-summary').textContent=state.session?state.session.members.length+' 席已分工':'等待入席';modelWarning();
  }
  function modelWarning(){if(!state.session){$('model-warning').hidden=true;return;}const values=state.session.members.map(id=>state.session.models?.[id]).filter(Boolean);let message='';if(values.length<state.session.members.length)message='还有席位没选模型。';else if(new Set(values).size<Math.min(3,values.length))message='至少选择三个不同模型，才能交叉判断。';else if(state.runMode==='execute'&&!state.session.path)message='先给这张圆桌选择项目文件夹。';$('model-warning').textContent=message;$('model-warning').hidden=!message;$('send').disabled=!!message||!!state.run;}
  async function saveModel(member,value){state.modelSaving=true;renderSeats();try{const updated=await api('/api/sessions/'+state.session.id+'/update',{models:{...state.session.models,[member]:value}});Object.assign(state.session,updated);const index=state.sessions.findIndex(item=>item.id===updated.id);if(index>=0)state.sessions[index]=updated;}catch(error){toast(error.message);}finally{state.modelSaving=false;renderSeats();}}
  async function loadModels(force=false){$('refresh-models').disabled=true;try{const data=await api('/api/models'+(force?'?refresh=1':''));state.models=data.models;$('model-status').textContent=data.models.length?data.models.length+' 个模型可选':'没有读到可用模型';renderSeats();}catch(error){$('model-status').textContent='模型列表未连接';toast(error.message);}finally{$('refresh-models').disabled=false;}}
  function updateSession(session,messages=[],run=null,replace=false){state.session=session;state.run=run;$('app').dataset.hasSession='true';if(replace)state.messages.clear();for(const message of messages)state.messages.set(message.id,message);document.title=session.title+' · 灵感圆桌';renderProject();renderSessions();renderMessages(true);renderSeats();stageState();$('draft').disabled=!!run;$('stop').hidden=!run;$('send').hidden=!!run;modelWarning();}
  function connectEvents(id){if(state.events)state.events.close();const events=new EventSource('/api/sessions/'+id+'/events');state.events=events;events.addEventListener('snapshot',event=>{if(state.session?.id===id){const data=JSON.parse(event.data);updateSession(data.session,data.messages,data.run,true);}});events.addEventListener('patch',event=>{if(state.session?.id===id){const data=JSON.parse(event.data);updateSession(data.session,data.messages,data.run,false);}});events.onerror=()=>{if(state.session?.id===id){$('connection').hidden=false;$('connection').textContent='连接正在恢复，记录和文件不会丢失。';}};events.onopen=()=>{$('connection').hidden=true;};}
  async function selectSession(id){if(state.session?.id===id)return;state.follow=true;try{const data=await api('/api/sessions/'+id);updateSession(data.session,data.messages,data.run,true);connectEvents(id);localStorage.setItem('roundtable:last',id);}catch(error){toast(error.message);}}
  function openCreate(){state.createPath='';$('create-title').value='';$('create-project-name').textContent='尚未选择';$('create-project-path').textContent='执行席只会在这里工作';$('invite-list').replaceChildren();for(const [id,info] of Object.entries(state.members)){const label=node('label','invite'),input=node('input');input.type='checkbox';input.value=id;input.checked=true;const image=node('img');image.src=portraits[id];image.alt='';label.append(input,image,node('span','',info.name));$('invite-list').append(label);}$('create-dialog').showModal();setTimeout(()=>$('create-title').focus(),60);}

  $('create-form').onsubmit=async event=>{event.preventDefault();if(!state.createPath)return toast('先选择或新建项目文件夹');const members=[...$('invite-list').querySelectorAll('input:checked')].map(item=>item.value);try{const session=await api('/api/sessions',{title:$('create-title').value,members,path:state.createPath});state.sessions.unshift(session);$('create-dialog').close();renderSessions();await selectSession(session.id);}catch(error){toast(error.message);}};
  $('choose-project').onclick=pickCreateProject;$('create-project').onclick=makeCreateProject;$('close-create').onclick=()=>$('create-dialog').close();$('new-session').onclick=openCreate;$('welcome-new').onclick=openCreate;$('session-filter').oninput=renderSessions;$('refresh-models').onclick=()=>loadModels(true);$('project-bind').onclick=bindCurrentProject;$('guard-bind').onclick=bindCurrentProject;$('project-open').onclick=()=>revealProject(state.session?.path);$('compose-project').onclick=()=>revealProject(state.session?.path);
  function setSeats(collapsed){$('app').dataset.seatsCollapsed=String(collapsed);$('toggle-seats').title=collapsed?'展开席位':'收起席位';$('toggle-seats').setAttribute('aria-label',$('toggle-seats').title);localStorage.setItem('roundtable:seats-collapsed',String(collapsed));}
  $('toggle-seats').onclick=()=>setSeats($('app').dataset.seatsCollapsed!=='true');$('timeline').onscroll=()=>{const timeline=$('timeline');state.follow=timeline.scrollHeight-timeline.scrollTop-timeline.clientHeight<120;syncJumpLatest();};$('jump-latest').onclick=()=>{state.follow=true;$('timeline').scrollTo({top:$('timeline').scrollHeight,behavior:'smooth'});};
  for(const button of document.querySelectorAll('[data-run-mode]'))button.onclick=()=>{state.runMode=button.dataset.runMode;for(const item of document.querySelectorAll('[data-run-mode]'))item.classList.toggle('active',item===button);$('compose-state').textContent=state.runMode==='execute'?'先判断，再执行，再验证':'只收拢方案，不改文件';modelWarning();};
  $('composer').onsubmit=async event=>{event.preventDefault();if(!state.session||state.run)return;const text=$('draft').value.trim();if(!text)return;const saved=text;$('draft').value='';$('draft').disabled=true;try{await api('/api/sessions/'+state.session.id+'/send',{text,mode:state.runMode});}catch(error){$('draft').value=saved;$('draft').disabled=false;toast(error.message);}};$('stop').onclick=async()=>{if(state.session&&state.run)try{await api('/api/sessions/'+state.session.id+'/stop',{});}catch(error){toast(error.message);}};$('draft').onkeydown=event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();$('composer').requestSubmit();}};
  async function boot(){setSeats(localStorage.getItem('roundtable:seats-collapsed')!=='false');try{const data=await api('/api/bootstrap');state.token=data.token;state.members=data.members;state.sessions=data.sessions;$('back-app').href=data.gatewayURL||$('back-app').href;renderSessions();renderSeats();loadModels();const last=localStorage.getItem('roundtable:last'),chosen=state.sessions.find(item=>item.id===last)||state.sessions[0];if(chosen)await selectSession(chosen.id);}catch(error){$('connection').hidden=false;$('connection').textContent=error.message;}finally{setTimeout(()=>{$('splash').classList.add('done');$('app').classList.add('ready');$('app').inert=false;},480);}}
  boot();
})();
