#!/usr/bin/env bash
# Runs outside the App bundle so a gateway restart or App replacement cannot
# strand the update halfway through. The launcher copies this file into the
# external SuperPinkie state directory before starting it.
set -eu

CURRENT_PID="${1:-0}"
APP_PATH="${2:-/Applications/超級碧琪.app}"
STATE_ROOT="${PINKIE_STATE_ROOT:-$HOME/Library/Application Support/SuperPinkie}"
CONFIG_FILE="${PINKIE_CONFIG_ROOT:-$HOME/.config/super-pinkie}/install.env"
MANAGED_REPO="$STATE_ROOT/repository"
LOG_DIR="$STATE_ROOT/logs"
LOG_FILE="$LOG_DIR/updater.log"
LOCK_DIR="$STATE_ROOT/updates/manual-update.lock"

mkdir -p "$LOG_DIR" "$STATE_ROOT/updates"
exec >>"$LOG_FILE" 2>&1

notify() {
  local message="$1"
  /usr/bin/osascript -e "display notification \"${message//\"/\\\"}\" with title \"超級碧琪\"" >/dev/null 2>&1 || true
}

reopen_app() {
  if [[ -d "$APP_PATH" ]]; then
    /usr/bin/open "$APP_PATH" >/dev/null 2>&1 || true
  fi
}

gateway_listener_pids() {
  /usr/sbin/lsof -nP -a -iTCP:18789 -sTCP:LISTEN -Fp 2>/dev/null \
    | sed -n 's/^p//p' | sort -u
}

gateway_executable_identity() {
  local pid="$1"
  # The first txt vnode is the process executable. Device + inode distinguish
  # an old process from a new App binary installed at the exact same pathname.
  /usr/sbin/lsof -nP -a -p "$pid" -d txt -FDin 2>/dev/null | awk '
    /^f/ { if (started) exit; started=1; next }
    started && /^D/ { device=substr($0,2); next }
    started && /^i/ { inode=substr($0,2); next }
    started && /^n/ { print device "|" inode "|" substr($0,2); exit }
  '
}

gateway_listener_matches_identity() {
  local pid="$1" expected="$2"
  [[ "$(gateway_executable_identity "$pid")" == "$expected" ]] || return 1
  gateway_listener_pids | grep -qx "$pid"
}

stop_exact_clekk_gateway() {
  local pid identity executable deadline remaining=""
  while IFS= read -r pid; do
    [[ "$pid" =~ ^[0-9]+$ ]] && (( pid > 1 )) || continue
    identity="$(gateway_executable_identity "$pid")"
    executable="${identity#*|}"
    executable="${executable#*|}"
    # Never signal a process merely because it owns port 18789. This exact
    # private bundle layout proves that it is a CLE Kk/SuperPinkie gateway.
    case "$executable" in
      *.app/Contents/Resources/SuperPinkie/runtime/bin/node) ;;
      *)
        echo "refusing to stop non-CLE-Kk listener pid=$pid executable=$executable"
        return 1
        ;;
    esac
    gateway_listener_matches_identity "$pid" "$identity" || continue
    echo "stopping exact CLE Kk gateway pid=$pid identity=$identity"
    kill -TERM "$pid" 2>/dev/null || return 1
    deadline=$((SECONDS + 8))
    while gateway_listener_matches_identity "$pid" "$identity"; do
      (( SECONDS < deadline )) || break
      sleep 0.1
    done
    if gateway_listener_matches_identity "$pid" "$identity"; then
      # Revalidate the mapped vnode immediately before the hard stop, so PID
      # reuse or a new process at the same path can never be killed by mistake.
      kill -KILL "$pid" 2>/dev/null || return 1
      deadline=$((SECONDS + 3))
      while gateway_listener_matches_identity "$pid" "$identity"; do
        (( SECONDS < deadline )) || break
        sleep 0.1
      done
    fi
    gateway_listener_matches_identity "$pid" "$identity" && return 1
  done < <(gateway_listener_pids)

  remaining="$(gateway_listener_pids)"
  [[ -z "$remaining" ]]
}

cleanup() {
  rmdir "$LOCK_DIR" >/dev/null 2>&1 || true
}

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  echo "$(date '+%F %T') another manual update is already running"
  notify "已经有一个更新任务在运行"
  reopen_app
  exit 0
fi
trap cleanup EXIT
trap 'notify "更新已中断，正在打开现有版本"; reopen_app; exit 1' HUP INT TERM

echo "$(date '+%F %T') detached update started; old pid=$CURRENT_PID app=$APP_PATH"

# The native launcher exits immediately after spawning us. Waiting here keeps
# the old bundle and its managed gateway out of the replacement transaction.
deadline=$((SECONDS + 120))
while [[ "$CURRENT_PID" =~ ^[0-9]+$ ]] && (( CURRENT_PID > 1 )) && kill -0 "$CURRENT_PID" 2>/dev/null; do
  if (( SECONDS >= deadline )); then
    echo "old App did not exit before timeout"
    notify "旧版没有安全退出，本次没有更新"
    reopen_app
    exit 1
  fi
  sleep 0.25
done

# The gateway is intentionally detached from the native App during ordinary
# relaunches. For an explicit update, stop its exact executable before any App
# files are replaced; otherwise the new UI silently reconnects to old code.
if ! stop_exact_clekk_gateway; then
  echo "gateway could not be stopped without risking another process"
  notify "旧网关无法安全停止，本次没有更新"
  reopen_app
  exit 1
fi

REPO=""
if [[ -f "$CONFIG_FILE" ]]; then
  # install.env is generated by install-full.sh and contains shell-escaped
  # local paths only. Keep using an existing source checkout when available.
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  if [[ -n "${PINKIE_REPO:-}" && -d "$PINKIE_REPO/.git" && -x "$PINKIE_REPO/update-full.sh" ]]; then
    REPO="$PINKIE_REPO"
  fi
fi

if [[ -z "$REPO" ]]; then
  REPO="$MANAGED_REPO"
  if [[ ! -d "$REPO/.git" ]]; then
    DOWNLOAD_DIR="$(mktemp -d "$STATE_ROOT/repository-download.XXXXXX")"
    if ! git clone --branch main --single-branch https://github.com/Cle0726/super-pinkie.git "$DOWNLOAD_DIR"; then
      echo "clone failed"
      notify "更新下载失败，旧版没有被改动"
      reopen_app
      exit 1
    fi
    if [[ -e "$REPO" ]]; then
      mv "$REPO" "$DOWNLOAD_DIR.previous"
    fi
    mv "$DOWNLOAD_DIR" "$REPO"
  fi
fi

branch="$(git -C "$REPO" branch --show-current 2>/dev/null || true)"
branch="${branch:-main}"
if ! git -C "$REPO" fetch --tags origin || ! git -C "$REPO" pull --ff-only origin "$branch"; then
  echo "git fast-forward failed for $REPO"
  notify "Git 拉取没有完成，旧版没有被改动"
  reopen_app
  exit 1
fi

if PINKIE_APP_ROOT="$(dirname "$APP_PATH")" "$REPO/update-full.sh"; then
  echo "$(date '+%F %T') detached update completed"
  notify "更新完成，正在重新打开"
  reopen_app
  exit 0
fi

echo "$(date '+%F %T') installer failed; install-full.sh handled App rollback"
notify "更新失败，已保留或恢复旧版"
reopen_app
exit 1
