#!/usr/bin/env bash
# Runs outside the App bundle so a gateway restart or App replacement cannot
# strand the update halfway through. The launcher copies this file into the
# external SuperPinkie state directory before starting it.
set -eu

CURRENT_PID="${1:-0}"
APP_PATH="${2:-/Applications/超級碧琪.app}"
STATE_ROOT="${PINKIE_STATE_ROOT:-$HOME/Library/Application Support/SuperPinkie}"
CONFIG_FILE="${PINKIE_CONFIG_ROOT:-$HOME/.config/super-pinkie}/install.env"
MANAGED_REPO="$STATE_ROOT/repository"
LOG_DIR="$STATE_ROOT/logs"
LOG_FILE="$LOG_DIR/updater.log"
LOCK_DIR="$STATE_ROOT/updates/manual-update.lock"

mkdir -p "$LOG_DIR" "$STATE_ROOT/updates"
exec >>"$LOG_FILE" 2>&1

notify() {
  local message="$1"
  /usr/bin/osascript -e "display notification \"${message//\"/\\\"}\" with title \"超級碧琪\"" >/dev/null 2>&1 || true
}

reopen_app() {
  if [[ -d "$APP_PATH" ]]; then
    /usr/bin/open "$APP_PATH" >/dev/null 2>&1 || true
  fi
}

cleanup() {
  rmdir "$LOCK_DIR" >/dev/null 2>&1 || true
}

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  echo "$(date '+%F %T') another manual update is already running"
  notify "已经有一个更新任务在运行"
  reopen_app
  exit 0
fi
trap cleanup EXIT
trap 'notify "更新已中断，正在打开现有版本"; reopen_app; exit 1' HUP INT TERM

echo "$(date '+%F %T') detached update started; old pid=$CURRENT_PID app=$APP_PATH"

# The native launcher exits immediately after spawning us. Waiting here keeps
# the old bundle and its managed gateway out of the replacement transaction.
deadline=$((SECONDS + 120))
while [[ "$CURRENT_PID" =~ ^[0-9]+$ ]] && (( CURRENT_PID > 1 )) && kill -0 "$CURRENT_PID" 2>/dev/null; do
  if (( SECONDS >= deadline )); then
    echo "old App did not exit before timeout"
    notify "旧版没有安全退出，本次没有更新"
    reopen_app
    exit 1
  fi
  sleep 0.25
done

REPO=""
if [[ -f "$CONFIG_FILE" ]]; then
  # install.env is generated by install-full.sh and contains shell-escaped
  # local paths only. Keep using an existing source checkout when available.
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  if [[ -n "${PINKIE_REPO:-}" && -d "$PINKIE_REPO/.git" && -x "$PINKIE_REPO/update-full.sh" ]]; then
    REPO="$PINKIE_REPO"
  fi
fi

if [[ -z "$REPO" ]]; then
  REPO="$MANAGED_REPO"
  if [[ ! -d "$REPO/.git" ]]; then
    DOWNLOAD_DIR="$(mktemp -d "$STATE_ROOT/repository-download.XXXXXX")"
    if ! git clone --branch main --single-branch https://github.com/Cle0726/super-pinkie.git "$DOWNLOAD_DIR"; then
      echo "clone failed"
      notify "更新下载失败，旧版没有被改动"
      reopen_app
      exit 1
    fi
    if [[ -e "$REPO" ]]; then
      mv "$REPO" "$DOWNLOAD_DIR.previous"
    fi
    mv "$DOWNLOAD_DIR" "$REPO"
  fi
fi

branch="$(git -C "$REPO" branch --show-current 2>/dev/null || true)"
branch="${branch:-main}"
if ! git -C "$REPO" fetch --tags origin || ! git -C "$REPO" pull --ff-only origin "$branch"; then
  echo "git fast-forward failed for $REPO"
  notify "Git 拉取没有完成，旧版没有被改动"
  reopen_app
  exit 1
fi

if PINKIE_APP_ROOT="$(dirname "$APP_PATH")" "$REPO/update-full.sh"; then
  echo "$(date '+%F %T') detached update completed"
  notify "更新完成，正在重新打开"
  reopen_app
  exit 0
fi

echo "$(date '+%F %T') installer failed; install-full.sh handled App rollback"
notify "更新失败，已保留或恢复旧版"
reopen_app
exit 1
